from tkinter import *
root1=Tk()
root1.title("Window1")
root1.geometry("200x200+200+150")
root2=Tk()
root2.title("window2")
root2.geometry("200x200+500+150")
a=StringVar()
def enter():
    c=a.get()
    label1=Label(root2,text=c,fg='green',bg='black',font=20).pack()
textbox=Entry(root1,textvariable=a).pack()
button1=Button(root1,text="Enter",fg='green',bg='black',command=enter).pack()
mymenu=Menu(root1)
mymenu.add_cascade(label="File")
mymenu.add_cascade(label="Edit")
mymenu.add_cascade(label="View")
mymenu.add_cascade(label="Run")
mymenu.add_cascade(label="Format")
mymenu2=Menu(root2)
mymenu2.add_cascade(label="Fil2")
mymenu2.add_cascade(label="View2")
mymenu2.add_cascade(label="Edi2")
mymenu2.add_cascade(label="Run2")
root2.config(menu=mymenu2)
root1.config(menu=mymenu)
root1.mainloop()
